//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIX_Milica_Karetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Floor { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public string Engagement { get; set; }
        public string Salary { get; set; }
    }
}
